runtime: python313

default_expiration: "10m"

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /io
  script: main.app
  secure: always
