# Copyright 2021 Bradley D. Nelson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: go123

default_expiration: "1m"

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: always

- url: /favicon(.*)
  static_files: static/favicon\1
  upload: static/favicon.*
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /(.*).html
  static_files: \1.html
  upload: (.*).html
  secure: always

- url: /serial
  static_files: serial.html
  upload: serial.html
  secure: always

- url: /(.*).js
  static_files: \1.js
  upload: (.*).js
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
